const MALE_ANIMALS = [
  "Rato",
  "Hamster",
  "Esquilo",
  "Camundongo",
  "Castor",
  "Gabiru",
  "Porquinho-da-índia",
  "Tatu",
  "Coelho",
  "Furão",
  "Porco-espinho",
  "Ouriço",
  "Lêmure",
  "Morcego",
  "Esquilo-voador",
  "Arminho",
];

const FEMALE_ANIMALS = [
  "Marmota",
  "Capivara",
  "Chinchila",
  "Topeira",
  "Ratazana",
  "Lontra",
  "Lebre",
  "Doninha",
  "Rata",
  "Fuinha",
  "Camundonga",
  "Equidna",
];

const NEUTRAL_ADJECTIVES = [
  "Serelepe",
  "Tchola",
  "Sapeca",
  "Mequetrefe",
  "Besta",
  "Triste",
  "Infeliz",
  "Inteligente",
  "Vidente",
  "Banguela",
  "Cegueta",
  "Nerdola",
  "Carente",
  "de iPhone",
  "Grande",
  "Paia",
  "Ciclista",
  "Motorista",
  "Captalista",
  "Comunista",
  "Socialista",
  "Anarquista",
  "Terraplanista",
  "Conspiracionista",
  "Capacitista",
  "Cientista",
  "Monarquista",
  "Futurista",
  "Carioca",
  "Paulista",
  "Taxista",
  "Petista",
  "Jovem",
  "de Schrödinger",
  "do BTS",
  "da Twitch",
  "Youtuber",
];

const MALE_ADJECTIVES = [
  "Deprimido",
  "Bobão",
  "Espertinho",
  "Emburrado",
  "Estranho",
  "Preguiçoso",
  "Inchado",
  "Transtornado",
  "Cabuloso",
  "Parrudo",
  "Maluco",
  "Doidão",
  "Burro",
  "Pidão",
  "Barato",
  "Fedido",
  "Curioso",
  "Fofoqueiro",
  "Capacho",
  "Matemático",
  "Viciado",
  "Mesquinho",
  "Voador",
  "Anão",
  "Armado",
  "Motoqueiro",
  "Piloto",
  "Vascaíno",
  "Místico",
  "Quântico",
  "Túlio",
  "Twitteiro",
];

const FEMALE_ADJECTIVES = [
  "Deprimida",
  "Bobona",
  "Espertinha",
  "Emburrada",
  "Estranha",
  "Preguiçosa",
  "Inchada",
  "Transtornada",
  "Cabulosa",
  "Parruda",
  "Maluca",
  "Doidona",
  "Burra",
  "Barata",
  "Curiosa",
  "Fofoqueira",
  "Matemática",
  "Viciada",
  "Mesquinha",
  "Pidona",
  "Anã",
  "Voadora",
  "Armada",
  "Motoqueira",
  "Pilota",
  "Mística",
  "Quântica",
  "Twitteira",
];

function random<T>(array: T[]) {
  return array[Math.floor(Math.random() * array.length)];
}

export function generatePlayerName() {
  const animal = random([...MALE_ANIMALS, ...FEMALE_ANIMALS]);

  const adjective = random([
    ...NEUTRAL_ADJECTIVES,
    ...(MALE_ANIMALS.includes(animal) ? MALE_ADJECTIVES : FEMALE_ADJECTIVES),
  ]);

  return `${animal} ${adjective}`;
}
